nikolatriki/giveaways

- app/controllers/giveaways_controller.rb
- app/views/giveaways/new.html.erb
- config/routes.rb
Created the view for the new action in the controller, with form and corresponding routes.
Created the create action in the controller using strong params.
> New and create actions

- config/routes.rb
Link to task: https://www.notion.so/Use-of-RESTful-routes-using-resources-helper-2f9a3dba15db48f28bcc143ab60e4025
> Refactor Giveaways routes with resources helper

- app/javascript/css/application.scss
- app/javascript/packs/application.js
- app/views/giveaways/index.html.erb
- package.json
- yarn.lock
Link to task: https://www.notion.so/Add-Bulma-css-framework-and-Font-Awesome-770a2d78607140539042b42c2c4d6388
> Add Bulma and Font Awesome via webpacker

- app/javascript/css/application.scss
- app/javascript/packs/application.js
- app/views/giveaways/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- package.json
- yarn.lock
Link to task: https://www.notion.so/Redesign-of-the-index-page-da9c479c68154e1483a0ebec09ce52f4
> Create navbar css element and redesign of index page

- app/views/giveaways/index.html.erb
Link to task: https://www.notion.so/Redesign-of-the-index-page-da9c479c68154e1483a0ebec09ce52f4
> Added columns and box css elements on index page

- app/javascript/navBar.js
- app/javascript/packs/application.js
Notion task: https://www.notion.so/Add-javascript-in-Navbar-burger-element-1f37ea431ea44bd9b6fb4e82c2dce25b
> Added javascript to Bulma burger element in navbar

- app/views/giveaways/index.html.erb
- app/views/giveaways/show.html.erb
- app/views/shared/_navbar.html.erb
Notion task: https://www.notion.so/Redesign-of-the-index-and-show-page-8d53adacf3164493b1184834bf3e217b
> Redesign of index page added css to show and refactor navbar partial

- app/views/giveaways/edit.html.erb
- app/views/giveaways/index.html.erb
- app/views/giveaways/new.html.erb
- app/views/giveaways/show.html.erb
- app/views/shared/_navbar.html.erb
Notion task: https://www.notion.so/Refactor-giveaways-new-and-edit-view-59bcc393ba06427ea4a4d336df16ba95
> Refactor giveaways new and edit view

- app/models/comment.rb
- app/models/giveaway.rb
- app/views/giveaways/show.html.erb
- config/routes.rb
- db/migrate/20210826132427_create_comments.rb
- db/schema.rb
- test/fixtures/comments.yml
- test/models/comment_test.rb
Notion task: https://www.notion.so/Add-comments-to-giveaways-show-view-4b0d1c1ffdff4181b5ce8bf4248e6008
> Display Comments and create comments routes

- Gemfile
- Gemfile.lock
- app/models/giveaway.rb
- spec/factories/comments.rb
- spec/factories/giveaways.rb
- spec/models/giveaway_spec.rb
Notion task: https://www.notion.so/Impement-Faker-gem-and-basic-model-giveaway-tests-62b5ba6573074d02a304f5bc9ca8853a
> Implement Faker gem, create model giveaway spec and factory

- app/javascript/css/application.scss
- app/views/comments/new.html.erb
- app/views/giveaways/_form.html.erb
Notion task: https://www.notion.so/Implement-error-messages-server-and-client-side-9dbb80df2832411d96c9c25551bcef98
> Refactor field with error messages for giveaways and comments

- spec/models/comment_spec.rb
Notion task: https://www.notion.so/Write-spec-for-Comment-Model-740703a53d22474d9476d7b35df05e06
> Create Comment Model spec

- db/seeds.rb
- spec/models/comment_spec.rb
Notion task: https://www.notion.so/Create-seed-file-with-Faker-571cd522226147f6bebef18eaec62d67
> Create seed file for populating the database

- Gemfile.lock
Ref: https://www.moncefbelyamani.com/understanding-the-gemfile-lock-file/#platforms
> Add darwin platform for OSX

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20210907202633_create_users.rb
- db/migrate/20210907214806_add_index_to_users_email.rb
- db/migrate/20210908113754_add_password_digest_to_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/views/giveaways/show.html.erb_spec.rb
Notion task: https://www.notion.so/Create-User-Model-963ca014de9b4f7a9d9936e4817e5a01
> Create Model User with validations

- app/controllers/users_controller.rb
- app/views/users/_form.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/controllers/users_controller_spec.rb
Notion task: https://www.notion.so/Create-Users-Controller-765378fefa224434b93ba19323b3788d
> Create Users Controller actions, routes and view

- app/views/layouts/application.html.erb
- app/views/shared/_flash.html.erb
Notion task: https://www.notion.so/Implement-Flash-messages-for-sessions-a585afd35e354730a84c5c9af02911a2
> Create flash partial for display messages

- app/controllers/sessions_controller.rb
- app/helpers/sessions_helper.rb
- app/views/sessions/new.html.erb
- config/routes.rb
- spec/helpers/sessions_helper_spec.rb
- spec/requests/sessions_spec.rb
- spec/views/sessions/new.html.erb_spec.rb
Notion task: https://www.notion.so/Create-Session-controller-with-routes-and-views-a20314cb7ffc4242a87b226455c5b23a
> Create Sessions controller with routes and view

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- app/views/shared/_navbar.html.erb
Notion taks:https://www.notion.so/Session-Deny-logged-in-users-to-log-in-or-sign-up-again-d2d38b2cefc04677be73a85c2ca5a753
> Implement logged_in_notice for login and signup

- app/models/giveaway.rb
- app/models/user.rb
- db/migrate/20210920193042_add_user_to_giveaways.rb
- db/schema.rb
- spec/models/giveaway_spec.rb
- spec/models/user_spec.rb
Notion task: https://www.notion.so/Create-User-Giveaway-models-association-3bb8fcf4c49d4d2db4ee1ec6c2245092
> User- Giveaway models association

- app/controllers/claims_controller.rb
- app/controllers/giveaways_controller.rb
- app/models/claim.rb
- app/models/giveaway.rb
- app/models/user.rb
- app/views/giveaways/_footer.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20211114223943_create_claims.rb
- db/migrate/20211114225155_add_claimed_to_giveaways.rb
- db/migrate/20211115203650_add_uniq_constraints_in_claims_table.rb
- db/schema.rb
- spec/controllers/claims_controller_spec.rb
- spec/controllers/giveaways_controller_spec.rb
- spec/factories/claims.rb
- spec/factories/pictures.rb
- spec/models/claim_spec.rb
- spec/models/giveaway_spec.rb
- spec/models/user_spec.rb
- spec/views/users/show.html.erb_spec.rb
NT: https://www.notion.so/Implement-Model-Claim-fd8151e905bb43eab638746960eb7b60
> Create model Claim, controller, claimed attribut to Giveaway

- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- config/routes.rb
NT:https://www.notion.so/Dashboard-redirect-to-dashboard-after-Sign-in-and-Sign-up-17d32b51011b4515945d3427642bb590
> Dashboard: Redirect to dashboard home after user Sign in and Sign up

- app/views/users/show.html.erb
- spec/views/users/show.html.erb_spec.rb
NT: https://www.notion.so/Refactor-User-show-view-public-profile-722c4ac5eec941d7a0e3e976c4717a89
> Refactor user show view and added specs

- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/views/contacts/new.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20211211224343_create_contacts.rb
- db/schema.rb
- spec/controllers/contacts_controller_spec.rb
- spec/factories/contacts.rb
- spec/models/contact_spec.rb
- spec/views/contacts/contacts.html.erb_spec.rb
- spec/views/users/show.html.erb_spec.rb
NT: https://www.notion.so/Contact-Us-functionality-35672c88c4c24886a8c322751cb557ea
> Contact Us Functionality

- Gemfile
- Gemfile.lock
- app/controllers/claims_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/claim_mailer.rb
- app/views/claim_mailer/new_claim.html.erb
- app/views/claim_mailer/new_claim.text.erb
- app/views/giveaways/index.html.erb
- app/views/layouts/mailer.html.erb
- app/views/layouts/mailer.text.erb
- config/environments/development.rb
- spec/fixtures/claim_mailer/new_claim
- spec/mailers/claim_mailer_spec.rb
- spec/mailers/previews/claim_mailer_preview.rb
https://www.notion.so/Claim-Mailer-Implement-Letter-Opener-gem-for-email-delivery-in-development-be103ff5242a4c85bff4b8ad028e036a
> Claim Mailer functionality using letter_opener

- config/environments/production.rb
https://www.notion.so/Implement-mailing-service-for-production-d8f3eea0103745019606624cdcce7134
> Production Mailer with Gmail

- app/views/shared/_navbar.html.erb
- config/environments/production.rb
NT: https://www.notion.so/Production-image-asset-not-displayed-on-Heroku-d90fe58351ca44e683b9e775a9dbf2e0
> Logo fix for heroku
